### ISSUE TITLE
悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友

### ISSUE THREAD

**Issue by flaviegd** [renjie-feng-trash/fengrenjie#2]
这几天我是在厕所大便时手机刷头条还是腾讯新闻时看到他的新闻的（当时新闻用了他的全名），已经过去这么久了，我也已经找到自己可以一生相伴的男人。
我现在要谢谢这个男人，当时我在他俩之间选择了我男人，然后我们一起打拼，现在我们有了自己幸福的小家庭。
       当时不知道feng是对我真的动了情还是怎的，他竟然说可以为了我不去美国马里兰大学，在蒙特利尔找个数学研究所我们组织家庭生小孩云云，还好我当时年龄比他大，加上我这个人有点福尔摩斯上身，发现了他几次骗我，所以我劝他还是安安心心去美国深造吧，哦弥陀佛就摆脱他了。
       说说他的事吧，我们是在qq认识的不靠谱吧，第一次见面是在康大guy那条路上，第一印象不太好，我就想回家，他拉着我说去他家坐坐，后面大家可以脑补了，其实第一次他紧张还是啥的竟然没有成功。他有点失望（这真的跟他现在一日4次还能把人搞散架不能比啊）这也可能是我没选他的原因，我觉得他根本不行。当时他骗我说他是康大的留学生，读完书想留在这里移民就业，他还问我会计好就业吗？后来不知道为什么对他动了怜悯之心，答应他继续当他的炮友。然后他还求我给他继续介绍别的女的，我也是傻就介绍了我的一个女同学，同学回来数落了我一顿，说他见完面就带她回公寓要发生关系，后来就不了了之了，然后他还在网上发布希望包养女留学生的帖子。我就跟他说不要再见了，因为我当时也有不少追求者真的不想在他身上浪费时间，结果他跑到我住的地方求我不要抛弃他，没了我他在蒙特利尔这样的苦寒之地没法活云云。哎，真是奥斯卡奖的演技。我们又继续保持那种关系，期间我认识了现在的男人，我男人也知道frj的存在。frj就老说我男友睡了他的女人，我也只能是笑笑。
        后来他到美国后还常qq我让我去美国找他，我就劝他在美国找人吧，忘了我吧！
        之所以写那么多，也是醉了！没想到他当时奉劝我的一句话竟然一语成谶：“常在河边走，哪有不湿鞋！”

**Comment by sjtuherisson** [comment]
。。。随手点开的issue，tql

**Comment by flaviegd** [comment]
那时认识的他真的跟现在网上瓜的这个他不太一样，他当时非常害怕感染HIV，说如果他被HIV了就太可惜了他的DNA，连吓带骗的要求我去医院检查了两次（吓得医院里的医生以为我真是HIV感染者）。
然后他在麦基尔大学代课教大一新生线性代数还是什么，当时学生留言打分也是中规中矩，好像有学生抱怨他的英语口音，他跟我说校园里确实有很漂亮的中国女留学生，但是他当时信誓旦旦的说，他作为老师是严禁跟女学生有师生恋的，没想到回国他的前妻竟然是他的学生。
不过他那时真的很可怜：我在他家给他做过一次饭，他很感动。寒冬腊月零下十几甚至零下几十度也没件棉袄大衣，更别说加拿大鹅了，所以他经常感冒生病拉肚子，春天他就鼻子过敏。他还常常穿着他在美国Johns Hopkins University的校服（就是照片里经常能看见的那件蓝色有帽子的外套，估计在那里他经历了什么，让他非常以那件衣服为荣，他显摆了几次无奈我真的对美国的大学知之甚少没当场认出来，让他难堪了好一阵）走路去麦基尔上班上课，当时他跟我说麦基尔里有个什么数学大牛，他经常去听大牛的讲课，就是经常早上起不来。
他说他认识我之前根本没办法做研究，整天浑浑噩噩，睡到自然醒，paper也写不出来，他当时说他的老板就是他美国大学的那个advisor: S. Zelditch经常给他加任务，弄不出来他压力很大，是我拯救了他，自从认识我他有了工作和生存的动力，搞得我现在回想起来好像我“上辈子拯救银河系”。
现在我在想如果我当时选择了他，他会不会伤害得我很深呢？估计会在蒙特利尔劈腿一辈子？答案是否定的，因为加拿大女人是非常珍贵的，也是非常强悍的，她们在苦寒之地顽强独立地生存惯了，辨识渣男的能力不是瓜中那些涉世未深的中国小姑娘可比，其中的中国女人更为珍贵=中国熊猫，老外都以有中国人女友为荣，而且在西方社会，劈腿的代价非常昂贵。社会对待工作中的性骚扰也是非常严厉的，这也是他在美国大学骚扰TA不成功的道理，西方人只有我们称为下层的烂人才滥交（一包烟一瓶啤酒就能搞掂），一般平头百姓正常人即使是同性恋都早早回家跟自己的伴侣和和睦睦的生活。

**Comment by sjtuherisson** [comment]
差一步人生就天差地别了。。。

**Comment by EasonMa** [comment]
> 那时认识的他真的跟现在网上瓜的这个他不太一样，他当时非常害怕感染HIV，说如果他被HIV了就太可惜了他的DNA，连吓带骗的要求我去医院检查了两次（吓得医院里的医生以为我真是HIV感染者）。
> 然后他在麦基尔大学代课教大一新生线性代数还是什么，当时学生留言打分也是中规中矩，好像有学生抱怨他的英语口音，他跟我说校园里确实有很漂亮的中国女留学生，但是他当时信誓旦旦的说，他作为老师是严禁跟女学生有师生恋的，没想到回国他的前妻竟然是他的学生。
> 不过他那时真的很可怜：我在他家给他做过一次饭，他很感动。寒冬腊月零下十几甚至零下几十度也没件棉袄大衣，更别说加拿大鹅了，所以他经常感冒生病拉肚子，春天他就鼻子过敏。他还常常穿着他在美国Johns Hopkins University的校服（就是照片里经常能看见的那件蓝色有帽子的外套，估计在那里他经历了什么，让他非常以那件衣服为荣，他显摆了几次无奈我真的对美国的大学知之甚少没当场认出来，让他难堪了好一阵）走路去麦基尔上班上课，当时他跟我说麦基尔里有个什么数学大牛，他经常去听大牛的讲课，就是经常早上起不来。
> 他说他认识我之前根本没办法做研究，整天浑浑噩噩，睡到自然醒，paper也写不出来，他当时说他的老板就是他美国大学的那个advisor: S. Zelditch经常给他加任务，弄不出来他压力很大，是我拯救了他，自从认识我他有了工作和生存的动力，搞得我现在回想起来好像我“上辈子拯救银河系”。
> 现在我在想如果我当时选择了他，他会不会伤害得我很深呢？估计会在蒙特利尔劈腿一辈子？答案是否定的，因为加拿大女人是非常珍贵的，也是非常强悍的，她们在苦寒之地顽强独立地生存惯了，辨识渣男的能力不是瓜中那些涉世未深的中国小姑娘可比，其中的中国女人更为珍贵=中国熊猫，老外都以有中国人女友为荣，而且在西方社会，劈腿的代价非常昂贵。社会对待工作中的性骚扰也是非常严厉的，这也是他在美国大学骚扰TA不成功的道理，西方人只有我们称为下层的烂人才滥交（一包烟一瓶啤酒就能搞掂），一般平头百姓正常人即使是同性恋都早早回家跟自己的伴侣和和睦睦的生活。

感谢科普

**Comment by LawlietZe** [comment]
....瞧我发现了什么

**Comment by ykk648** [comment]
。。。上班时间刷github就给我推这个？？？？

**Comment by clayzzzzzzzzzz** [comment]
6666666666666666666666

**Comment by hazlehu** [comment]
知乎追来

**Comment by renjie-feng-trash** [comment]
从这几天知道的越来越多的事例来看，冯很惯用这种套路，伤害人也会装可怜。恭喜你做了正确的选择。不过这个issue的重点似乎在他那方面不行，xswl

**Comment by yoyo837** [comment]
渣男该锤死，女人也要更爱自己。

**Comment by ddzy** [comment]
有意思

**Comment by jewelcai** [comment]
git马上可以看小黄文了

**Comment by songwentong** [comment]
约炮要谨慎,小心艾滋病

**Comment by tengzh** [comment]
老外都以有中国人女友为荣???

**Comment by sjtuherisson** [comment]
PKU通报出来了

**Comment by yoyo837** [comment]
@sjtuherisson 贴链接

**Comment by sjtuherisson** [comment]
> @sjtuherisson 贴链接

我在侠客岛看到的，搜了一下只有网易的新闻
https://news.163.com/19/1211/15/F04IUBU60001899O.html

**Comment by ZHANGneuro** [comment]
从北大解聘了，看他将来去哪吧

**Comment by 1286058233** [comment]
痕迹要留下啊冯狗儿

**Comment by xuyanging** [comment]
这也太秀了吧.....

**Comment by xdr940** [comment]
这货是不是有病啊,性瘾什么的???

**Comment by xuhangxuhang** [comment]
这人一天不和女生睡觉活不下去吗？科研压力那么大哪来的精力搞这些事情啊

**Comment by ZHANGneuro** [comment]
肯定是有这方面强烈需求，才能不顾一切的追求。

**Comment by muyuuuu** [comment]
打开github第一眼.......就给我看了这个........

**Comment by muyuuuu** [comment]
打开github的第一眼是想学习的，.........，给我推荐了这个，太强了

**Comment by wrick198** [comment]
就不怕，他找到你

**Comment by iam57-2020** [comment]
震撼我🐎

**Comment by mushrup** [comment]
Montreal的数学比Maryland好吧。。。

**Comment by suichukewan** [comment]
666啊

**Comment by qq475742653** [comment]
版主的留言，真是毁三观啊。留过学的人，都这么孤独吗？孤独感中找到无拘无束的性自由。这是多么厉害的荷尔蒙？还是破罐破摔？
看来 感性=愚味 是真的。

**Comment by geekyouth** [comment]
我不知道一个人、尤其是个女人，可以有多寂寞或者多随便才会愿意找个不靠谱的渣男yp。。。真的是毁三观

**Comment by yoyo837** [comment]
一般普通人男女，对于对方条件不至于特别差，长相不讨厌，对方追求自己基本会考虑接受。

这种情况应该是不知道对方是渣的，受骗的，但要为自己没有认真谈，了解不够充分就进行下一步而负责。

**Comment by qq475742653** [comment]
现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。
    多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子；
    忙着打发时间吗？还是更有面子。还是更加没有原则。
    像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。
    这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。
    只是丢掉一个烂苹果，再找到一个烂香蕉而已。

**Comment by geekyouth** [comment]
> ```
> 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。
> 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子；
> 忙着打发时间吗？还是更有面子。还是更加没有原则。
> 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。
> 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。
> 只是丢掉一个烂苹果，再找到一个烂香蕉而已。
> ```

-----------------------------------------------------------------------------------------------------------

就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？

你咋不说现在的人类是毁掉的一代呢？

**Comment by jewelcai** [comment]
> > ```
> > 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。
> > 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子；
> > 忙着打发时间吗？还是更有面子。还是更加没有原则。
> > 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。
> > 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。
> > 只是丢掉一个烂苹果，再找到一个烂香蕉而已。
> > ```
> 
> 就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？
> 
> 你咋不说现在的人类是毁掉的一代呢？

这人是个奇葩  你还理他？
<img width="942" alt="屏幕快照 2019-12-13 下午1 41 16" src="https://user-images.githubusercontent.com/8166517/70772065-507b6300-1dae-11ea-8f43-ac23a29d823f.png">

**Comment by Desmond-Liu** [comment]
在这里还能吃瓜

**Comment by qq475742653** [comment]
截了张图想证明什么。老子行的正，走的端，说的在理，不像你这等脑残玩意。
  &nbsp;
 随口就说别人奇葩，我想说你是个贱货。算是礼尚往来了。
 &nbsp;
 
&nbsp;
 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"jewelcai"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月13日(星期五) 中午1:42
 收件人:&nbsp;"renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;;
 抄送:&nbsp;"475742653"<475742653@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
 主题:&nbsp;Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2)

 

  现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子； 忙着打发时间吗？还是更有面子。还是更加没有原则。 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。 只是丢掉一个烂苹果，再找到一个烂香蕉而已。  
就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？
 
你咋不说现在的人类是毁掉的一代呢？
 
这人是个奇葩 你还理他？

**Comment by jewelcai** [comment]
> 截了张图想证明什么。老子行的正，走的端，说的在理，不像你这等脑残玩意。 &nbsp; 随口就说别人奇葩，我想说你是个贱货。算是礼尚往来了。 &nbsp; &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jewelcai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月13日(星期五) 中午1:42 收件人:&nbsp;"renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送:&nbsp;"475742653"<475742653@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子； 忙着打发时间吗？还是更有面子。还是更加没有原则。 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。 只是丢掉一个烂苹果，再找到一个烂香蕉而已。 就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？ 你咋不说现在的人类是毁掉的一代呢？ 这人是个奇葩 你还理他？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

想证明你这种弱智SB 说别人是毁掉的一代 说别人脏  自己干的事却十分猥琐  还有点滑稽。

**Comment by qq475742653** [comment]
你妈的，王八蛋玩意。像鬼缠身，滚蛋




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jewelcai"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 下午4:49
收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 
抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2)



 
截了张图想证明什么。老子行的正，走的端，说的在理，不像你这等脑残玩意。 &nbsp; 随口就说别人奇葩，我想说你是个贱货。算是礼尚往来了。 &nbsp; &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jewelcai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月13日(星期五) 中午1:42 收件人:&nbsp;"renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送:&nbsp;"475742653"<475742653@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子； 忙着打发时间吗？还是更有面子。还是更加没有原则。 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。 只是丢掉一个烂苹果，再找到一个烂香蕉而已。 就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？ 你咋不说现在的人类是毁掉的一代呢？ 这人是个奇葩 你还理他？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
想证明你这种弱智SB 说别人是毁掉的一代 说别人脏  自己干的事却十分猥琐  还有点滑稽。

**Comment by jewelcai** [comment]
> 你妈的，王八蛋玩意。像鬼缠身，滚蛋
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:49 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 截了张图想证明什么。老子行的正，走的端，说的在理，不像你这等脑残玩意。 &nbsp; 随口就说别人奇葩，我想说你是个贱货。算是礼尚往来了。 &nbsp; &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jewelcai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月13日(星期五) 中午1:42 收件人:&nbsp;"renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送:&nbsp;"475742653"<475742653@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子； 忙着打发时间吗？还是更有面子。还是更加没有原则。 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。 只是丢掉一个烂苹果，再找到一个烂香蕉而已。 就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？ 你咋不说现在的人类是毁掉的一代呢？ 这人是个奇葩 你还理他？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 想证明你这种弱智SB 说别人是毁掉的一代 说别人脏 自己干的事却十分猥琐 还有点滑稽。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你这种素质的人  现实生活中十分猥琐  估计憋坏了吧  操你妈。

**Comment by qq475742653** [comment]
滚蛋吧，垃圾




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jewelcai"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 下午4:51
收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 
抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2)



 
你妈的，王八蛋玩意。像鬼缠身，滚蛋
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:49 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 截了张图想证明什么。老子行的正，走的端，说的在理，不像你这等脑残玩意。 &nbsp; 随口就说别人奇葩，我想说你是个贱货。算是礼尚往来了。 &nbsp; &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jewelcai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月13日(星期五) 中午1:42 收件人:&nbsp;"renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送:&nbsp;"475742653"<475742653@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子； 忙着打发时间吗？还是更有面子。还是更加没有原则。 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。 只是丢掉一个烂苹果，再找到一个烂香蕉而已。 就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？ 你咋不说现在的人类是毁掉的一代呢？ 这人是个奇葩 你还理他？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 想证明你这种弱智SB 说别人是毁掉的一代 说别人脏 自己干的事却十分猥琐 还有点滑稽。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你这种素质的人  现实生活中十分猥琐  估计憋坏了吧  操你妈。

**Comment by jewelcai** [comment]
> 滚蛋吧，垃圾
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:51 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 你妈的，王八蛋玩意。像鬼缠身，滚蛋 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:49 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 截了张图想证明什么。老子行的正，走的端，说的在理，不像你这等脑残玩意。 &nbsp; 随口就说别人奇葩，我想说你是个贱货。算是礼尚往来了。 &nbsp; &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jewelcai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月13日(星期五) 中午1:42 收件人:&nbsp;"renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送:&nbsp;"475742653"<475742653@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子； 忙着打发时间吗？还是更有面子。还是更加没有原则。 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。 只是丢掉一个烂苹果，再找到一个烂香蕉而已。 就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？ 你咋不说现在的人类是毁掉的一代呢？ 这人是个奇葩 你还理他？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 想证明你这种弱智SB 说别人是毁掉的一代 说别人脏 自己干的事却十分猥琐 还有点滑稽。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你这种素质的人 现实生活中十分猥琐 估计憋坏了吧 操你妈。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

看看你的留言 都是扣帽子  好好在你偏执的世界里活着吧  可怜  滚蛋吧弱智

**Comment by qq475742653** [comment]
看看你的留言吧。你跟死变态有什么区别。半斤八两的玩意，别五十步笑百步了，当此为止。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jewelcai"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 下午4:54
收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 
抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2)



 
滚蛋吧，垃圾
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:51 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 你妈的，王八蛋玩意。像鬼缠身，滚蛋 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:49 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 截了张图想证明什么。老子行的正，走的端，说的在理，不像你这等脑残玩意。 &nbsp; 随口就说别人奇葩，我想说你是个贱货。算是礼尚往来了。 &nbsp; &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jewelcai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月13日(星期五) 中午1:42 收件人:&nbsp;"renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送:&nbsp;"475742653"<475742653@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 现在的90后啊。真是毁掉的一代。知识掌握再多有什么用。 多学学中华传统文化吧。即使没学过传统文化，也应知道：性的卫生安全、心理承受、利益的多少、名声名利、社交圈、原则；最为原始的也会考虑：性能力、相处性格、相貌、家境、面子； 忙着打发时间吗？还是更有面子。还是更加没有原则。 像墙头草一样随风摆动，摆动着光着的屁股谁都可以来。 这么不爱惜自己的人，能找到什么好的男人，好的心灵安慰。 只是丢掉一个烂苹果，再找到一个烂香蕉而已。 就因为某些老鼠屎扰乱了游戏规则，你就一刀切合适吗？ 你咋不说现在的人类是毁掉的一代呢？ 这人是个奇葩 你还理他？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 想证明你这种弱智SB 说别人是毁掉的一代 说别人脏 自己干的事却十分猥琐 还有点滑稽。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你这种素质的人 现实生活中十分猥琐 估计憋坏了吧 操你妈。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
看看你的留言 都是扣帽子  好好在你偏执的世界里活着吧  可怜  滚蛋吧弱智

**Comment by jewelcai** [comment]
> 为止

你都快40的人了  认知还停留在扣帽子的阶段  谁才是变态呢？

**Comment by qq475742653** [comment]
看看你有多不服气。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jewelcai"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 下午4:59
收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 
抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2)



 
为止
  
你都快40的人了  认知还停留在扣帽子的阶段  谁才是变态呢？

**Comment by jewelcai** [comment]
> 看看你有多不服气。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:59 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 为止 你都快40的人了 认知还停留在扣帽子的阶段 谁才是变态呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我一直对大龄猥琐男是服气的

**Comment by qq475742653** [comment]
看看你有多不服气。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jewelcai"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 下午5:07
收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 
抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2)



 
看看你有多不服气。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jewelcai"<notifications@github.com&gt;; 发送时间: 2019年12月13日(星期五) 下午4:59 收件人: "renjie-feng-trash/fengrenjie"<fengrenjie@noreply.github.com&gt;; 抄送: "475742653"<475742653@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [renjie-feng-trash/fengrenjie] 悄悄上来了，我是frj在加拿大蒙特利尔麦基尔大学读博士后时的炮友 (#2) 为止 你都快40的人了 认知还停留在扣帽子的阶段 谁才是变态呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我一直对大龄猥琐男是服气的

**Comment by ZHANGneuro** [comment]
水军全来了，该回的回，不该回的不回。放什么在github是你自己的权利，除非官方下架，谁说也没用。
